// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbtkfbduftfuyawcytno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhidGtmYmR1ZnRmdXlhd2N5dG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MDY0MzEsImV4cCI6MjA1MDE4MjQzMX0.71_WekQ2q8uOPVxoisCcoIXXPenq6sVQ5dja8RCHfO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);